channels:
- conda-forge
dependencies:
- python=3.12.7
- pip<=24.2
- pip:
  - mlflow==3.1.1
  - cloudpickle==3.1.1
  - numpy==2.3.1
  - pandas==2.3.1
  - scikit-learn==1.5.2
  - scipy==1.16.0
name: mlflow-env
